## Basic Configuration
baseurl = "https://walker-harrison.com/"
languageCode = "en"

title = ""
theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

# summarylength = 30

#paginate = 5

## Site Settings
[params]
    author = "Author"
    title = "Title"
    # description = "..."
    authorimage = "/img/headshot.jpg"
    dateformat = "Jan 2, 2006"

    # sidebar, copyright & license
    #logoimage = "/img/hugo.png"
    copyright = "htr3n"
    since = 2019
    license = "CC BY-SA 4.0"
    licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    showBuiltWith = true

    # https://highlightjs.org
    highlightjs = true
    highlightjslanguages = ["r", "yaml"]
    highlightjsstyle = "github"
    
    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"
    hideReadingTime = true
    mainSections = ["posts"]

## Social Accounts
[params.social]
    github = "WalkerHarrison"
    instagram = "walkwearscrocs"
    linkedin = "walker-harrison-11a36b6b"
    twitter = "walkwearscrocs"
    email = "walkerharrison1000@gmail.com"
    # gravatar = "your-email@example.com"
    # pgpkey = "<path-to-your-key-in-/static>"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 200
    identifier = "posts"
    url = "/posts/"
##[[menu.main]]
    ##name = "Portfolio"
    ##identifier = "portfolio"
    ##weight = 300
    ##url = "/portfolio/"
[[menu.main]]
    name = "Consulting"
    identifier = "consulting"
    weight = 300
    url = "/consulting/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 100
    url = "/about/"
